version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/build/

hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: ec2-user
#  ApplicationStart:
#    - location: deploy.sh
#      runas: ec2-user
